merge_base_with = 'main'

[[linter]]
code = 'RUFF'
include_patterns = [
    '**/*.py',
    '**/*.pyi',
]
exclude_patterns = [
    'src/torch_onnx/_torchscript_converter.py',  # 3rd party code
]
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'ruff_linter',
    '--config=pyproject.toml',
    '--show-disable',
    '@{{PATHSFILE}}',
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'ruff==0.4.4',
]
is_formatter = true

[[linter]]
code = 'RUFF-FORMAT'
include_patterns = [
    '**/*.py',
]
exclude_patterns = [
    'src/torch_onnx/_torchscript_converter.py',  # 3rd party code
]
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'ruff_format_linter',
    '--config=pyproject.toml',
    '--',
    '@{{PATHSFILE}}',
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'ruff==0.4.4',
]
is_formatter = true

[[linter]]
code = 'MYPY'
include_patterns = [
    'torch_onnx/**/*.py',
    'torch_onnx/**/*.pyi',
]
exclude_patterns = [
]
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'mypy_linter',
    '--config=pyproject.toml',
    '--show-disable',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    '--requirement=requirements/lintrunner/requirements.txt',
]
